// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKUqBAfKV2cUigp49Y6Pne9_zf8v8WLJs',
    appId: '1:556196335680:web:82b3690d27bb2fda224fa5',
    messagingSenderId: '556196335680',
    projectId: 'pantrypal-5985692',
    authDomain: 'pantrypal-5985692.firebaseapp.com',
    storageBucket: 'pantrypal-5985692.firebasestorage.app',
    measurementId: 'G-WJF9G6B2X0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAh4NStRtLfumoOo3auoljx80-JEIkDRLE',
    appId: '1:556196335680:android:114211106d9a9c92224fa5',
    messagingSenderId: '556196335680',
    projectId: 'pantrypal-5985692',
    storageBucket: 'pantrypal-5985692.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTfqYTEdGDl6MjZ3mWy5iL5TzEVZ5zmo0',
    appId: '1:556196335680:ios:061c06f06e26d7a7224fa5',
    messagingSenderId: '556196335680',
    projectId: 'pantrypal-5985692',
    storageBucket: 'pantrypal-5985692.firebasestorage.app',
    iosBundleId: 'com.example.loginPage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTfqYTEdGDl6MjZ3mWy5iL5TzEVZ5zmo0',
    appId: '1:556196335680:ios:061c06f06e26d7a7224fa5',
    messagingSenderId: '556196335680',
    projectId: 'pantrypal-5985692',
    storageBucket: 'pantrypal-5985692.firebasestorage.app',
    iosBundleId: 'com.example.loginPage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKUqBAfKV2cUigp49Y6Pne9_zf8v8WLJs',
    appId: '1:556196335680:web:1884c7e2f36a70d8224fa5',
    messagingSenderId: '556196335680',
    projectId: 'pantrypal-5985692',
    authDomain: 'pantrypal-5985692.firebaseapp.com',
    storageBucket: 'pantrypal-5985692.firebasestorage.app',
    measurementId: 'G-WWC4W8RG4K',
  );
}
